### ISSUE TITLE
Introduce Middleware

### ISSUE THREAD

**Issue by ravage84** [Ali1/cakephp-brute-force-protection#1]
Hi, we are currently evaluating your BruteForceShield for some of our CakePHP applications.
By the way we found your solution through [your CakeDC Users issue](https://github.com/CakeDC/users/issues/784)

I think it would be useful if this plugin would provide some of the current funktionality through a [middleware](https://book.cakephp.org/4/en/controllers/middleware.html) additionally to the component.

For example the functionality could be split in two:

1. Checking if a client is already blocked and block it
2. Validating a request and blocking, if necessary

While the second makes more sense to be used for only a few routes, e.g. the login page, the first one could be applied to each request.

**Comment by Ali1** [comment]
It would do well as middleware although it's not something I'm actively developing. It has been working for me as is.
